#!/bin/bash

function getWordpress {

    echo "Downloading wordpress:"
    curl -O# https://de.wordpress.org/latest-de_DE.zip
    tar -xzf latest-de_DE.zip
    rm latest-de_DE.zip


}



if [ "$1" = "get" ]

then
    getWordpress
fi


if [ "$1" = "update" ]

then
  # GET WORDPRESS
  getWordpress

  echo "Copy files to directory"
  # COPY merge
  cp -aR wordpress/* .

  rm -rf wordpress

  echo "Done!"

fi

if [ "$1" = "install" ]

then
    getWordpress
    mv wordpress/* .
    rm -rf wordpress
fi
